# Generated by Django 4.2.30 on 2026-04-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExplanationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrapper', models.CharField(max_length=20)),
                ('location_id', models.CharField(max_length=100)),
                ('forecast_for_utc', models.DateTimeField()),
                ('explanation_markdown', models.TextField()),
                ('citations_json', models.JSONField(default=list)),
                ('generated_at_utc', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
