# Generated by Django 4.2.30 on 2026-04-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=50)),
                ('location_id', models.CharField(max_length=100)),
                ('wrapper', models.CharField(choices=[('beach', 'Beach'), ('fishing', 'Fishing'), ('surf', 'Surf'), ('ecosystem', 'Ecosystem')], max_length=20)),
                ('forecast_for_utc', models.DateTimeField()),
                ('predicted_at_utc', models.DateTimeField()),
                ('risk_score', models.FloatField()),
                ('risk_bucket', models.CharField(max_length=50)),
                ('uncertainty_score', models.FloatField(blank=True, null=True)),
                ('top_factors', models.JSONField(default=list)),
                ('source_artifact_uri', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'indexes': [models.Index(fields=['wrapper', 'location_id', 'forecast_for_utc'], name='risk_risksn_wrapper_72e762_idx')],
            },
        ),
    ]
